# coding: utf-8

"""
    Deepcuts API

    An API to access music artist metadata and recommendations.

    The version of the OpenAPI document: v0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deepcuts_sdk.models.genre import Genre  # noqa: E501


class TestGenre(unittest.TestCase):
    """Genre unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenre(self):
        """Test Genre"""
        # inst = Genre()


if __name__ == "__main__":
    unittest.main()
