# coding: utf-8

"""
    Deepcuts API

    An API to access music artist metadata and recommendations.

    The version of the OpenAPI document: v0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from deepcuts_sdk.models.body_deepcuts_recommend_albums_from_albums import (  # noqa: E501
    BodyDeepcutsRecommendAlbumsFromAlbums,
)


class TestBodyDeepcutsRecommendAlbumsFromAlbums(unittest.TestCase):
    """BodyDeepcutsRecommendAlbumsFromAlbums unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BodyDeepcutsRecommendAlbumsFromAlbums:
        """Test BodyDeepcutsRecommendAlbumsFromAlbums
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `BodyDeepcutsRecommendAlbumsFromAlbums`
        """
        model = BodyDeepcutsRecommendAlbumsFromAlbums()  # noqa: E501
        if include_optional:
            return BodyDeepcutsRecommendAlbumsFromAlbums(
                album_titles = [
                    ''
                    ],
                artist_names = [
                    ''
                    ],
                genres = [
                    'acoustic'
                    ]
            )
        else:
            return BodyDeepcutsRecommendAlbumsFromAlbums(
                album_titles = [
                    ''
                    ],
                artist_names = [
                    ''
                    ],
        )
        """

    def testBodyDeepcutsRecommendAlbumsFromAlbums(self):
        """Test BodyDeepcutsRecommendAlbumsFromAlbums"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
