FROM python:3.11-slim AS builder

RUN pip install pip-tools

COPY pyproject.toml .

# Install dependencies
RUN pip-compile --generate-hashes --output-file=requirements.txt pyproject.toml
RUN pip install -r requirements.txt

FROM python:3.11-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=builder /app /app

EXPOSE 8000
CMD ["python", "-m", "uvicorn", "deepcuts_api.main:create_app", "--factory", "--host", "0.0.0.0", "--port", "8000"]
